name: Matrix

on:
  workflow_dispatch

jobs:
  matrix-jobs:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        include:
          - index: 0
            total: 4
            os: ubuntu-latest
            java: 17
            java-version: 17
          - index: 1
            total: 4
            os: ubuntu-latest
            java: 21
            java-version: 21
          - index: 2
            total: 4
            os: windows-latest
            java: 17
            java-version: 17
          - index: 3
            total: 4
            os: windows-latest
            java: 21
            java-version: 21

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v3.14.1
        with:
          java-version: ${{ matrix.java-version }}
          distribution: microsoft

      - name: Print Matrix Info
        run: |
          echo "Index: ${{ matrix.index }}"
          echo "Total: ${{ matrix.total }}"
          echo "OS: ${{ matrix.os }}"
          echo "Java: ${{ matrix.java }}"
          echo "Java Version: ${{ matrix.java-version }}"

         
